filebrowser/urls.py
from django.conf.urls import *

urlpatterns = patterns('',
    
    # filebrowser urls
    url(r'^browse/$', 'filebrowser.views.browse', name="fb_browse"),
    url(r'^mkdir/', 'filebrowser.views.mkdir', name="fb_mkdir"),
    url(r'^upload/', 'filebrowser.views.upload', name="fb_upload"),
    url(r'^rename/$', 'filebrowser.views.rename', name="fb_rename"),
    url(r'^delete/$', 'filebrowser.views.delete', name="fb_delete"),
    url(r'^versions/$', 'filebrowser.views.versions', name="fb_versions"),
    
    url(r'^check_file/$', 'filebrowser.views._check_file', name="fb_check"),
    url(r'^upload_file/$', 'filebrowser.views._upload_file', name="fb_do_upload"),
    
)

inactive/databaseML2/urls.py
from django.conf.urls  import url
from . import views

app_name = "databaseML2"

urlpatterns = [

    url(r'database2/', views.database2, name='database2'),
#Water
    url(r'waterinput/$', views.IndexView.as_view(), name='index'),
    url(r'^waterinput/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='water_input-detail'),
    #/databaseML2/waterinput/add/
    url(r'waterinput/add/$', views.WaterInputCreate.as_view(), name='water_input-add'),
    #/databaseML2/waterinput/update/2/
    url(r'waterinput/update/(?P<pk>[0-9]+)/$', views.WaterInputUpdate.as_view(), name='water_input-update'),
    #/databaseML2/waterinput/delete/
    url(r'waterinput/delete/$', views.WaterInputDelete.as_view(), name='water_input-delete'),

#Electric
    url(r'electricinput/$', views.ElectricInputIndexView.as_view(), name='electric-index'),

    url(r'^electricinput/(?P<pk>[0-9]+)/$', views.ElectricInputDetailView.as_view(), name='electric_input-detail'),
    #/databaseML2/electricinput/add/
    url(r'electricinput/add/$', views.ElectricInputCreate.as_view(), name='electric_input-add'),
    #/databaseML2/electricinput/update/2/
    url(r'electricinput/update/(?P<pk>[0-9]+)/$', views.ElectricInputUpdate.as_view(), name='electric_input-update'),
    #/databaseML2/electricinput/delete/
    url(r'electricinput/delete/$', views.ElectricInputDelete.as_view(), name='electric_input-delete'),

#Natural Gas
    url(r'nat_gasinput/$', views.NatGasInputIndexView.as_view(), name='nat_gas-index'),
    url(r'^nat_gasinput/(?P<pk>[0-9]+)/$', views.NatGasInputDetailView.as_view(), name='nat_gas_input-detail'),
    #/databaseML2/nat_gasinput/add/
    url(r'nat_gasinput/add/$', views.NatGasInputCreate.as_view(), name='nat_gas_input-add'),
    #/databaseML2/nat_gasinput/update/2/
    url(r'nat_gasinput/update/(?P<pk>[0-9]+)/$', views.NatGasInputUpdate.as_view(), name='nat_gas_input-update'),
    #/databaseML2/nat_gasinput/delete/
    url(r'nat_gasinput/delete/$', views.NatGasInputDelete.as_view(), name='nat_gas_input-delete'),

#Solid Waste
    url(r'solid_wasteinput/$', views.SolidWasteInputIndexView.as_view(), name='solid_waste-index'),
    url(r'^solid_wasteinput/(?P<pk>[0-9]+)/$', views.SolidWasteInputDetailView.as_view(), name='solid_waste_input-detail'),
    #/databaseML2/nat_gasinput/add/
    url(r'solid_wasteinput/add/$', views.SolidWasteInputCreate.as_view(), name='solid_waste_input-add'),
    #/databaseML2/nat_gasinput/update/2/
    url(r'solid_wasteinput/update/(?P<pk>[0-9]+)/$', views.SolidWasteInputUpdate.as_view(), name='solid_waste_input-update'),
    #/databaseML2/nat_gasinput/delete/
    url(r'solid_wasteinput/delete/$', views.SolidWasteInputDelete.as_view(), name='solid_waste_input-delete'),
]

webapp/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin

admin.autodiscover()







urlpatterns = patterns(
    'webapp.views',
    (r'^$', 'viewHome'),
    (r'^participation-form$', 'viewParticipationForm'),
    (r'^home_api/select_section', 'selectHomePageSect')
)


#urlpatterns += patterns(
#    'databaseML.views',
#    url(r'^database/', include ('databaseML.urls')),
#    url(r'^', include ('databaseML.urls')),
#)

#urlpatterns += patterns(
#    'databaseML2.views',
#    url(r'^database2/', include ('databaseML2.urls', namespace="databaseML2")),
#    url(r'^', include ('databaseML2.urls', namespace="databaseML2")),
#)


# 9/10/2016 - Mauricio Leon - The one bellows simply makes the urls in
# city_metrics/ajax_urls.py available
urlpatterns += patterns(
    '',
    (r'^chart_api/', include('city_metrics.ajax_urls')),
)

urlpatterns += patterns(
    '',
    (r'^admin/imports/', include('admin_imports.urls')),
)

urlpatterns += patterns(
    '',
    url(r'^admin/filebrowser/', include('filebrowser.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEVELOPMENT:
    urlpatterns += patterns(
        '',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
        url(r'^customer_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.PROJECT_ROOT + '/customer_media'}),
    )

urlpatterns += patterns(
    'site_content.views',
    url(r'^(?P<aSlug>.*)$', 'viewDetail'),
)

inactive/databaseML2/views.py
# Create your views here.
from django.views import generic
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from city_metrics.models import *
from django.shortcuts import render, get_object_or_404


def database2(request):
        citys = City.objects.exclude
	return render(request, 'database_manager/home.html', {
                'citys': citys,
        })

#Water
class IndexView(generic.ListView):
    template_name = 'databaseML2/water_index.html'
    def get_queryset(self):
        return CityMetricsWaterInput.objects.all()

class DetailView(generic.DetailView):
    model = CityMetricsWaterInput
    template_name = 'databaseML2/water_detail.html'

class WaterInputCreate(CreateView):
    model = CityMetricsWaterInput
    fields = ["city_id", "year", "residential_water", "commercial_water", "industrial_water", "other_water"]
    sucess_url = reverse_lazy('databaseML2:index')

class WaterInputUpdate(UpdateView):
    model = CityMetricsWaterInput
    fields = ["city_id", "year", "residential_water", "commercial_water", "industrial_water", "other_water"]

class WaterInputDelete(DeleteView):
    model = CityMetricsWaterInput
    sucess_url = reverse_lazy('databaseML2:index')


#Electric

class ElectricInputIndexView(generic.ListView):
    model = CityMetricsElectricInput
    template_name = 'databaseML2/electric_index.html'
    def get_queryset(self):
        return CityMetricsElectricInput.objects.all()


class ElectricInputDetailView(generic.DetailView):
    model = CityMetricsElectricInput
    template_name = 'databaseML2/electric_detail.html'

class ElectricInputCreate(CreateView):
    model = CityMetricsElectricInput
    fields = ["city_id", "year"]
    sucess_url = reverse_lazy('databaseML2:electric-index')
    def get_absolute_url(self):
            return u'/electricinput/%d/' % self.id

class ElectricInputUpdate(UpdateView):
    model = CityMetricsElectricInput
    fields = ["city_id", "year"]

class ElectricInputDelete(DeleteView):
    model = CityMetricsElectricInput
    sucess_url = reverse_lazy('databaseML2:electric_index')


#Natural Gas

class NatGasInputIndexView(generic.ListView):
    template_name = 'databaseML2/nat_gas_index.html'
    def get_queryset(self):
        return CityMetricsNatGasInput.objects.all()

class NatGasInputDetailView(generic.DetailView):
    model = CityMetricsNatGasInput
    template_name = 'databaseML2/nat_gas_detail.html'

class NatGasInputCreate(CreateView):
    model = CityMetricsNatGasInput
    fields = ["city_id", "year"]

class NatGasInputUpdate(UpdateView):
    model = CityMetricsNatGasInput
    fields = ["city_id", "year"]

class NatGasInputDelete(DeleteView):
    model = CityMetricsNatGasInput
    sucess_url = reverse_lazy('databaseML2:nat_gas_index')

#Solid Waste

class SolidWasteInputIndexView(generic.ListView):
    template_name = 'databaseML2/solid_waste_index.html'
    def get_queryset(self):
        return CityMetricsSolidWasteInput.objects.all()

class SolidWasteInputDetailView(generic.DetailView):
    model = CityMetricsSolidWasteInput
    template_name = 'databaseML2/solid_waste_detail.html'

class SolidWasteInputCreate(CreateView):
    model = CityMetricsSolidWasteInput
    fields = ["city_id", "year"]

class SolidWasteInputUpdate(UpdateView):
    model = CityMetricsSolidWasteInput
    fields = ["city_id", "year"]

class SolidWasteInputDelete(DeleteView):
    model = CityMetricsSolidWasteInput
    sucess_url = reverse_lazy('databaseML2:solid_waste_index')

templates/databaseML2/detail.html
{% extends 'base.html' %}

{% block title %}Water Details{% endblock %}

{% block extraHead %}

    <link type="text/css" rel="stylesheet" href="/static/css/detail.css"/>
    <link rel="stylesheet" href="/static/fancybox/jquery.fancybox.css?v=2.1.5" type="text/css" media="screen"/>
    <script type="text/javascript" src="/static/fancybox/jquery.fancybox.pack.js?v=2.1.5"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $(".fancybox").fancybox();
        });
        $(document).ready(function () {
            $(".accordion").accordion({collapsible: true, heightStyle: "content", active: false});
        });
    </script>

{% endblock %}
{% block content %}

      <div id='content'>

<h1>{{ object.city_id }}</h1>
<p>{{ object.year }}</p>
<p>{{ object.residential_water }}</p>

<form action="/waterinput/add/">
    <input type="submit" value="UPDATE" />
</form>

<form action="waterinput/delete/">
    <input type="submit" value="DELETE" />
</form>

      </div>


{% endblock %}

templates/databaseML2/index.html
{% extends 'base.html' %}
{% load url from future %}
{% block extraHead %}

    <link type="text/css" rel="stylesheet" href="/static/css/detail.css"/>
    <link rel="stylesheet" href="/static/fancybox/jquery.fancybox.css?v=2.1.5" type="text/css" media="screen"/>
    <script type="text/javascript" src="/static/fancybox/jquery.fancybox.pack.js?v=2.1.5"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $(".fancybox").fancybox();
        });
        $(document).ready(function () {
            $(".accordion").accordion({collapsible: true, heightStyle: "content", active: false});
        });
    </script>

{% endblock %}
{% block content %}

      <div id='content'>

<p>TESTING</p>
  <ul>
    {% for CityMetricsWaterInput in object_list %}
      <li>
      <a href="{% url 'databaseML2:water_input-detail' CityMetricsWaterInput.id %}">{{ CityMetricsWaterInput.city_id }}, {{ CityMetricsWaterInput.year }}</a>
      </li>
    {% endfor %}
  </ul>


      </div>


{% endblock %}

templates/databaseML2/nat_gas_index.html
{% extends 'base.html' %}
{% load url from future %}
{% block extraHead %}

    <link type="text/css" rel="stylesheet" href="/static/css/detail.css"/>
    <link rel="stylesheet" href="/static/fancybox/jquery.fancybox.css?v=2.1.5" type="text/css" media="screen"/>
    <script type="text/javascript" src="/static/fancybox/jquery.fancybox.pack.js?v=2.1.5"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $(".fancybox").fancybox();
        });
        $(document).ready(function () {
            $(".accordion").accordion({collapsible: true, heightStyle: "content", active: false});
        });
    </script>

{% endblock %}
{% block content %}

      <div id='content'>

<p>TESTING</p>
  <ul>
    {% for CityMetricsWaterInput in object_list %}
      <li>
      <a href="{% url 'databaseML2:water_input-detail' CityMetricsWaterInput.id %}">{{ CityMetricsWaterInput.city_id }}, {{ CityMetricsWaterInput.year }}</a>
      </li>
    {% endfor %}
  </ul>


      </div>


{% endblock %}